# Generated by Django 4.0.6 on 2023-02-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0003_item_amount_item_needs_item_savings_item_wants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='item',
            name='text',
        ),
    ]
